on:
  push:
    tags:
    - '*'

name: Test tags

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git status; git describe --tags

    
