on:
  push:
    branches:
      - 'new_deploys'

name: Deploy to Staging Cloudfront

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "$GITHUB_REF"

    
